export {default as Home} from './Home'
export {default as LoginPage} from './Login'
export {default as Cart} from './Cart'
export {default as Pizza} from './Pizza'
export {default as RegisterPage} from './Register'
export {default as NotFound} from './NotFound'
export {default as Profile} from './Profile'